package enumerate;

public enum State {
    NONE,
    PHONE_RECEIVED,
    PHONE_OTP_VALIDATED,
    EMAIL_RECEIVED,
    EMAIL_OTP_VALIDATED,
    ID_RECEIVED,
    CURP_RECEIVED,
    CURP_VALIDATED,
    CURP_REPEATED,
    ZIPCODE_RECEIVED,
    ADDRESS_RECEIVED,
    SIGNATURE_RECEIVED,
    SELFIE_RECEIVED
}

